spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/strivelabs
    username: postgres
    password: $anjay1@2
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
         
  
   
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: sanjaykumarcool3@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    cache: false

server:
  servlet:
    session:
      timeout: 1800

app:
  otp:
    expiry-minutes: 5
    length: 6
  issuer-name: "Dual2FAAuth"

logging:
  level:
    com.example.dual2fauth: DEBUG